version: 2

sources:
  - name: raw_data
    description: "Raw data from the source system"
    database: zoomcamp_dbt
    schema: prod
    tables:
      - name: yellow_tripdata
      - name: green_tripdata
      - name: fhv_tripdata